### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by reverland** [reverland/blog-next#1]
- [X] tags/categories/archives support
- [x] feed
- [X] semantic ui style responsive theme
- [X] responsive navbar
- [x] syntax highlight(however, some bug for highlight.js)
- [x] styles for images/videos in posts
- [ ] toc
- [x] ghpages
- [ ] SEO: https://github.com/ktquez/vue-head

others may not support but not sure
- [ ] maxjax support
- [ ] disqus
- [ ] google analysis

**Comment by reverland** [comment]
More, I need a server that [properly configured](http://readystate4.com/2012/05/17/nginx-and-apache-rewrite-to-support-html5-pushstate/). github pages will always return 404

**Comment by reverland** [comment]
https://github.com/rafrex/spa-github-pages

**Comment by EmmanuelBeziat** [comment]
Hi!
Why would github pages return 404? On which element?
